### ISSUE TITLE
Place the new image in section 3 desktop

### ISSUE THREAD

**Issue by wahlstrommm** [Medieinstitutet/fed21d-grafiska-verktyg-croissant#104]
Seems like one picture is missing in the desktop version.

**Comment by JennyAnneHook** [comment]
Wich picture is lost? I can see the 3 cards, bread and "hands", are there more?

**Comment by wahlstrommm** [comment]
> Wich picture is lost? I can see the 3 cards, bread and "hands", are there more?

It seems like you guys have added it now. But can work on the placement of image. its the "hands pic" im referring to

**Comment by wahlstrommm** [comment]
> > Wich picture is lost? I can see the 3 cards, bread and "hands", are there more?
> 
> It seems like you guys have added it now. But can work on the placement of image. its the "hands pic" im referring to

@JennyAnneHook

**Comment by JennyAnneHook** [comment]
The "hands"-picture is added
